import Head from "next/head";
import { Toaster } from "react-hot-toast";
import { Props } from "./animals";
import prisma from "@/libs/prismadb";

import HeroSection from "@/components/pages/body/hero/HeroSection";
import CallToAction from "@/components/pages/body/CallToAction";
import AnimalExtinctionInformation from "@/components/pages/body/AnimalExtinctionInformation";
import AnimalFetchSlider from "@/components/pages/body/animals/AnimalFetchSlider";

export default function Home({ data }: Props) {
  return (
    <>
      <Head>
        <title>Animal ONG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <CallToAction />
      <AnimalExtinctionInformation />
      <AnimalFetchSlider data={data} />
      <Toaster />
    </>
  );
}

export async function getServerSideProps() {
  try {
    const res = await prisma.animal.findMany({
      select: {
        id: true,
        name: true,
        intAge: true,
        description: true,
        resumeDescription: true,
        images: true,
      },
    });

    const data = res;

    return {
      props: {
        data,
      },
    };
  } catch (error) {
    console.log(error);
  }
}
