import Head from "next/head";
import { Toaster } from "react-hot-toast";
import { Props } from "./animals";
import axios from "axios";

import HeroSection from "@/components/pages/body/hero/HeroSection";
import CallToAction from "@/components/pages/body/CallToAction";
import AnimalExtinctionInformation from "@/components/pages/body/AnimalExtinctionInformation";
import AnimalFetchSlider from "@/components/pages/body/animals/AnimalFetchSlider";

export default function Home({ data }: Props) {
  return (
    <>
      <Head>
        <title>Animal Adoption</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <CallToAction />
      <AnimalExtinctionInformation />
      <AnimalFetchSlider data={data} />
      <Toaster />
    </>
  );
}

export async function getStaticProps() {
  const res = await axios.get(`${process.env.MY_VARIABLE_API}/api/getanimals`);
  const data = res.data;

  return {
    props: {
      data: data.data,
    },
  };
}
